name: Test the Sil Kit Docker images

on:
  pull_request:
    branch: main

jobs:
  ubuntu-1804:
    name: Push Docker image to ghcr.io registry
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./containers/ci-ubuntu-18.04/
          build-contexts: |
            utils=./utils/
          file: ./containers/ci-ubuntu-18.04/Dockerfile
          push: false
          load: true
          tags: sil-kit-test:latest

      - name: Test Image
        run: |
          docker run -itd --name emmy_noether sil-kit-test:latest /bin/bash
          docker cp ./utils/image_tests.sh emmy_noether:/home/image_tests.sh
          docker exec -w /home/  emmy_noether sh image_tests.sh

